### ISSUE TITLE
Plugin Config, Incorrect Sequence

### ISSUE THREAD

**Issue by arrmo** [dougbw/coredns_omada#14]
Hi,

As outlined at https://github.com/coredns/coredns/issues/6262, it seems that this plugin should not be at the start of the config file, but rather right before `forward` ... agreed?

Thanks!

**Comment by dougbw** [comment]
Thanks for reporting this, I was aware that the order of the plugins was important but wasn't sure what the impact was as things generally seemed to be working for me.  I have updated the documentation and the latest docker images are also fixed.
