### ISSUE TITLE
Issues with Omada v5.12

### ISSUE THREAD

**Issue by arrmo** [dougbw/coredns_omada#16]
Hi,

I just updated to Omada v5.12 (officially released), and now coredns_omada seems to have issues? Or at least, I don't see to have local name resolution.

Is there a way to check for this, help debug?

Thanks!

**Comment by dougbw** [comment]
I suspect there has been an API change in the latest controller release - in the release notes it mentions open API changes.

I haven't updated my home network yet but will give it a go tonight and see what needs to be update in coredns_omada

**Comment by arrmo** [comment]
> I suspect there has been an API change in the latest controller release - in the release notes it mentions open API changes.

Was thinking exactly the same thing!

> I haven't updated my home network yet but will give it a go tonight and see what needs to be updated in coredns_omada

Sounds great! Yell if I can do anything at all to help.

Thanks!

**Comment by dougbw** [comment]
I have just raised a PR with what I think the fix is if you want to give it a go. I plan on getting it tested merged and published tonight if all goes to plan.

**Comment by arrmo** [comment]
Thanks! Sure, will give it a shot. Is it in another branch? If so, I'll pull that one, try it out.

**Comment by dougbw** [comment]
PR: https://github.com/dougbw/coredns_omada/pull/17
Branch: `fix/omada-5.12`

**Comment by arrmo** [comment]
Yep, spotted that 🤣. Thanks!

OK, pulled it, NP there. But ... build from coredns seems to pull the "stock" (tagged) version? I need to look more, how to build with the branch.

**Comment by arrmo** [comment]
Ok, updated `go.mod`, but it's complaining about version,
```
CGO_ENABLED=0  go build -v -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=ae2bbc29-dirty" -o coredns
core/plugin/zplugin.go:59:2: /opt/coredns_omada@v1.4.2: missing go.sum entry for go.mod file; to add it:
        go mod download /opt/coredns_omada
```
But then,
```
$ go mod download /opt/coredns_omada
go: malformed module path "/opt/coredns_omada": empty path element
```
That path really is correct 😆 

Thanks!

**Comment by dougbw** [comment]
To build from a specific branch you can check out that branch on your local clone of coredns_omada, then in the coredns repo add the following line into `go.mod` (updated with the correct path to coredns_omada repo):

```
replace github.com/dougbw/coredns_omada => /<local path>/coredns_omada
```

--------

I have built and tested this and it seems to be working correctly for me now. I have published the updated docker images if that is your thing. It was a small API change in the update which caused this (fix: https://github.com/dougbw/go-omada/commit/4e4b298eb9cc219771e3f67319e5f88dfc2774e3).

**Comment by arrmo** [comment]
Got it up and running, thanks! I don't have a docker image, rather a local build - but all seems to be good now, thanks!

BTW, on the [build instructions](https://github.com/dougbw/coredns_omada/blob/main/docs/build.md) ... why clone `coredns_omada` locally? It seems that is only used for local development, agreed? Meaning ... if `coredns/plugin.cfg` is modified, there is no need for the local repository - correct?

Thanks again.

**Comment by dougbw** [comment]
I think you are probably right there - to be honest I have never tested building it having only the coredns repo cloned. I will give it a go and update the documentation to separate out the build/local dev instructions.

**Comment by arrmo** [comment]
Thanks!
