### ISSUE TITLE
Disable HTTPS validation in CoreFile

### ISSUE THREAD

**Issue by gurhyj** [dougbw/coredns_omada#19]
Hi,  

Is it possible to set the "Disable HTTPS validation" in the CoreDNS CoreFile, I tried  both 

disable-https-verification  and disable_https_verification

**Comment by dougbw** [comment]
Hello. You can disable https verification through the `OMADA_DISABLE_HTTPS_VERIFICATION` environmental variable. It can't be set via the corefile.

See https://github.com/dougbw/coredns_omada/blob/main/docs/configuration.md#https-verification

**Comment by michnixweiss** [comment]
@dougbw sorry for picking this closed issue up. But I don't get where to put this environmental variable.
When searching for it only found hints for docker but not for source build version.

**Comment by michnixweiss** [comment]
Shame uppon me... Found it.
```
sudo OMADA_DISABLE_HTTPS_VERIFICATION="true". /coredns
```
