### ISSUE TITLE
linux/arm/v7 Docker image support for Raspberry Pi

### ISSUE THREAD

**Issue by Manicben** [dougbw/coredns_omada#21]
The plugin has worked a treat for my local DNS woes! I'm currently running it in Docker (Portainer) on a Raspberry Pi 4.
Unfortunately, my Pi OS is 32 bit and thus only runs armv7 based images, so I couldn't just pull the images on DockerHub.

Would it be possible to add `linux/arm/v7` images, or add the arch to the multi-platform images?

No changes are required on the `docker buildx` side other than adding `--platform linux/arm/v7`, which worked perfectly for me (i.e. `docker buildx build --platform linux/arm/v7 -t coredns-omada .`).

**Comment by dougbw** [comment]
Hi,

I originally built + published the container images to docker hub manually from my workstation, so was in the process of setting up a github actions workflow to build the images and publish to github container registry automatically. I actually forgot I was doing this but it includes arm v7 images and other than updating documentation to make users aware of the change I think its all ready to go.

https://github.com/dougbw/coredns_omada/pkgs/container/corends_omada

Let me know if you have any issues

**Comment by dougbw** [comment]
Documentation has been updated to point to the new container images. Hopefully these are working as expected.

**Comment by dougbw** [comment]
Note I had a typo in the package name initially as the images were published as corends_omada rather than coredns_omada - Please update the image name if you are using them as I will delete the incorrectly spelt one after a few weeks.
