### ISSUE TITLE
"found '0' sites: []" if controller URL has a trailing slash

### ISSUE THREAD

**Issue by veN1337** [dougbw/coredns_omada#22]
This is probably not a real issue but imho it should be some how documented.  
I had a trailing slash in my controller URL. This lead to coredna-omada not finding any sites and printed the following log:
`[INFO] plugin/omada: logging in...
[INFO] plugin/omada: found '0' sites: []
[INFO] plugin/omada: update: updating zones...`

Login succeeded and no more (error) logs were printed. It didn't matter if I had the actual site name configured or ".*".  
Removing the trailing slash fixed the problem and the site was found.

**Comment by dougbw** [comment]
Hi, thanks for letting me know. I will look in it this next time I am working an on update as it should be an easy fix to help avoid people running into config issues.

**Comment by dougbw** [comment]
I have fixed this in the go-omada package which is used to perform the API requests. The URLs are now built up using a proper join method to avoid this issue, and I have improved the error handling as the TP-Link controller API often returns a 200 where the response body contains an error.

 https://github.com/dougbw/go-omada/releases/tag/v0.5.0

I will bump the dependency on this project shortly.
