### ISSUE TITLE
[Feature Request] Allow . in DNS names

### ISSUE THREAD

**Issue by friggeri** [dougbw/coredns_omada#27]
I have a few security cameras I'd like to group together in a subdomain (as in `[location].cam.[domain]`), currently the period gets stripped [here](https://github.com/dougbw/go-omada/blob/main/dns.go#L12), would be great to have the option to not strip a `.`

**Comment by dougbw** [comment]
Hi. Adding a `.` in a DNS host generally indicates a sub domain. Although some DNS systems do support this arbitrarily adding dots to a given hostname it can have mixed results in some scenarios so I would be hesitant about implementing it for this project as it could lead to weird issues that would be difficult to track down.

See https://www.ietf.org/rfc/rfc1034.txt:
```
A domain is identified by a domain name, and consists of that part of
the domain name space that is at or below the domain name which
specifies the domain.  A domain is a subdomain of another domain if it
is contained within that domain.  This relationship can be tested by
seeing if the subdomain's name ends with the containing domain's name.
For example, A.B.C.D is a subdomain of B.C.D, C.D, D, and " ".
```

**Comment by friggeri** [comment]
Yes that's actually what I want to do: I'd like to be able to configure certain clients to all have a fqdn that is a subdomain of `cam.[domain]`

An alternative way of doing this would be to put them on a different lan where the host domain is `cam.[domain]`, but that comes with a bit of overhead, I was hoping to avoid doing that by being able to encoding that in the name field in Omada.

**Comment by dougbw** [comment]
I will take a look at this the next time I am working on an update, but my gut feeling is that its going to add too much complexity for what it is worth, so again would advise to go with the flat domain of `[location]-cam.[domain]`

**Comment by friggeri** [comment]
I ended up just creating multiple vlans with different domains, it was a bit of hassle but I actually like where things ended up. Thanks for getting me to do things "properly" ;)

**Comment by dougbw** [comment]
Glad you got it sorted!
