### ISSUE TITLE
Not working with ER7212PC

### ISSUE THREAD

**Issue by Raggamax72** [dougbw/coredns_omada#38]
I tried to get it working with the ER7212PC which is the omada router with integrated controller. But it does not seem to work. I could not find any info if this device even has an API..... :-(

**Comment by mikepell007** [comment]
I have the ER7212PC and did not have to do anything outside of the docs here.   FWIW it is v1.0 firmware 1.1.1

**Comment by Raggamax72** [comment]
> I have the ER7212PC and did not have to do anything outside of the docs here. FWIW it is v1.0 firmware 1.1.1

Sounds good.. so this is not the Problem i am having ;-) maybe someone could give me a little hint how i can start the container on a QNAP nas with the required parameters. Tried it from the shell but still get errors like

 plugin/omada: There is a Corefile configuration error:
plugin/omada: Key: 'config.Controller_url' Error:Field validation for 'Controller_url' failed on the 'required' tag
Key: 'config.Site' Error:Field validation for 'Site' failed on the 'required' tag

**Comment by mikepell007** [comment]
> plugin/omada: There is a Corefile configuration error: plugin/omada: Key: 'config.Controller_url' Error:Field validation for 'Controller_url' failed on the 'required' tag Key: 'config.Site' Error:Field validation for 'Site' failed on the 'required' tag

Make sure you are passing the url, username, and password as environment variables.  On Qnap, there is a screen to create and set environment variables (maybe under advanced?) when you create the container.  Basically all of the "--env" lines in the getting started guide.

**Comment by dougbw** [comment]
Hi, this does sound like you are not setting the environment variables correctly. As far as I am aware the ER7212PC controller should behave no different to the other hardware/software controller variants but please let me know if you run into issues.

The documentation shows how to run this in a [docker container](https://github.com/dougbw/coredns_omada/blob/main/docs/getting-started.md#docker) so providing you set the environment variables correctly it should start. Im not familiar with QNAP but the same principals should apply, so if you get stuck it might be worth trying to run the docker container on your local workstation first to get a better understanding of how it works.
