### ISSUE TITLE
Cant connect to Software controller as i cannot use port 443

### ISSUE THREAD

**Issue by shedunraid** [dougbw/coredns_omada#39]
Tried to get this up and running.  I am running my Omada controller on a Pi - and seemingly cant set port 443 for the controller HTPPS port.

Is there a way to customise this to use my controller URL & port?

Thanks

**Comment by dougbw** [comment]
Hi. The coredns-omada plugin doesn't care about which port the controller is running on. As long as you tell it the controllets hostname/IP + port it will work. 

How are you running coredns?

If you are using docker then you need to set the `OMADA_URL` environment variable to the correct value.

If you are running the coredns binary directly then it's the `controller_url` property in the Corefile, see https://github.com/dougbw/coredns_omada/blob/main/corefile-examples/standard/Corefile
