### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by arrmo** [dougbw/coredns_omada#4]
Hi,

Apologies - this may be me, but ... after the build, and configure, I end up with this error when trying to run coredns,
```
plugin/omada: site not found:
```

Any thoughts?

Thanks!

**Comment by arrmo** [comment]
On me - not sure how, but the site row got deleted.

**Comment by dougbw** [comment]
Thanks for raising this and I am glad you got it sorted! - I should make the code a bit more defensive in this area to provide better feedback when there are configuration issues, and a couple of the documentation/examples are also missing the `site` config entry which probably doesn't help.

I will aim to address this in the next release 👍
