### ISSUE TITLE
connect: connection refused

### ISSUE THREAD

**Issue by Hobbyflyer** [dougbw/coredns_omada#40]
running software SDN Controller on proxmox lxc (latest version)

starting docker container results in an error
plugin/omada: plugin/omada: Get "https://192.168.10.100/api/info": dial tcp 192.168.10.100:443: connect: connection refused

running docker in seperate lxc using portainer

need to specify port cause HW Controller uses 443 , software controller 8043
see also
* https://www.tp-link.com/de/support/faq/3281/
* https://www.tp-link.com/de/support/faq/3429/

**Comment by dougbw** [comment]
Hi, It looks like you need to set the `OMADA_URL` environment variable to `192.168.10.100:8043`

**Comment by Hobbyflyer** [comment]
Ok, thats it. so easy. tried the other way..  sometimes the problem is in front of the pc

Thanks
