### ISSUE TITLE
Feature Request: CNAME records

### ISSUE THREAD

**Issue by laheym** [dougbw/coredns_omada#42]
I love this plugin, but would it be possible to add a feature where the plugin loads a list of CNAME records for my local network zone?

for example, I have a local server with multiple services running in docker including an NGINX reverse proxy on port 80/443 that forwards traffic to the correct port depending on hostname of HTTP/S request.  For this to solution to work multiple hostnames must resolve to the same IP.  

In this example the A record would be populated from the omada clients list:
`server.omada.home A 10.0.0.5`
to get the reverse proxy to route to the correct container, I would need a CNAME (or A) record to be added to the local zone too:
`smokeping.omada.home CNAME server.omada.home`

**Comment by dougbw** [comment]
Hi. CoreDNS supports a file plugin where you can serve records from a file. See https://coredns.io/plugins/file/

**Comment by laheym** [comment]
thanks for the quick reply dougbw!  I was just looking at the coredns docs.

**Comment by laheym** [comment]
Feature is already present
