### ISSUE TITLE
no route to host

### ISSUE THREAD

**Issue by Sekkyo** [dougbw/coredns_omada#43]
Trying to get this up and running for the first time. I set up all the environment variables correctly, as it does display the https://IP_address environment variable for the Omada controller successfully.

Yet all I get is `connect: no route to host` spamming every second. What do I need to start debugging? Wondering if the virtual switch is routing traffic out to the LAN correctly.

Super appreciative of this project and the support you are providing us, @dougbw. This is a fantastic weekend project for those of us that want to map to device names around the house without having to resort to the dreaded hosts file hack.

**Comment by dougbw** [comment]
Hello, what environment are you running in? It sounds like a network/issue but I would need more details about your setup to help.

**Comment by Sekkyo** [comment]
Docker running in QNAP QuTS' Container Station. I gave it an IP on the same VLAN as the Omada Controller, bridged on a virtual switch like all my other Docker instances successfully work on the network.

I guess I have to keep fiddling.

**Comment by Sekkyo** [comment]
Here's some of the safe information I can share on how it is set up to run:

<img width="800" alt="Screenshot 2024-07-20 at 2 05 12 PM" src="https://github.com/user-attachments/assets/2e268094-bcc1-4585-84a8-71479114dbe9">
<img width="802" alt="Screenshot 2024-07-20 at 2 05 24 PM" src="https://github.com/user-attachments/assets/ef783b95-9632-4b00-affe-798779526239">
<img width="802" alt="Screenshot 2024-07-20 at 2 06 19 PM" src="https://github.com/user-attachments/assets/3d4f80a4-4ed9-4d28-ad30-31ded63f920f">
<img width="807" alt="Screenshot 2024-07-20 at 2 05 40 PM" src="https://github.com/user-attachments/assets/29266cca-0707-4d85-a5d0-6ec87dc56d45">
<img width="803" alt="Screenshot 2024-07-20 at 2 05 51 PM" src="https://github.com/user-attachments/assets/10d553b8-a01a-4938-87d1-81b658c98aba">
<img width="801" alt="Screenshot 2024-07-20 at 2 06 08 PM" src="https://github.com/user-attachments/assets/2b36f64d-5dfa-4ba8-8f40-fbf4da758191">

**Comment by Sekkyo** [comment]
Changing the Docker instance from the virtual network with a static IP to NAT lets it work, but that isn't the network topology I want. Still digging into why this Docker instance doesn't want to operate on the VLAN of the virtual network like all the other Docker images I use...

**Comment by dougbw** [comment]
It sounds like it has no outbound internet connection so is unable to reach the upstream DNS server 1.1.1.1. When you are setting the static IP address in bridge mode make sure you have set the default gateway correctly.

**Comment by Sekkyo** [comment]
Yeah, it's all correct. It just doesn't work. It's probably a bug in QNAP's virtual switch. They don't have the best software quality, so I'm going to close this and work it out with them. If I have any updates, I'll comment.

Appreciate all you do with this project. It's great, though I do have questions about how hosts get updated in CoreDNS. Is that part of the Docker config? It's able to pick up one host name from my Omada config, but not all of them. Maybe I need to go configure the host names in Omada.
