### ISSUE TITLE
Is appending the router's domain name really necessary?

### ISSUE THREAD

**Issue by reeseovine** [dougbw/coredns_omada#48]
This is a feature request based on opinion and not a bug.

I like having short, succinct hostnames so I can easily type them into a terminal, for example. Ease of typing is really important to me because I have some issues with fine motor skills but I still like to use a computer :P

I find having to type a domain like `computer.home.lan` instead of just `computer` or `computer.lan` takes ever-so-slightly more work that just doesn't feel worth it to me. I only have one site, my home network.

In Omada the domain *has* to have at least two parts to it. Maybe I don't understand DNS enough to know why this is required? I would appreciate someone dropping a link or explaining why if this is the case.

I tried implementing it myself by changing `update.go` ~~but it didn't seem to make anything different, weirdly.~~ it was a cache thing.

**Comment by dougbw** [comment]
The DHCP server will hand out the DNS domain suffix which will allow you to just type `computer` although this does depend on device / operating system. If you have assigned a static IP address on your device you can set the DNS search domain manually.

**Comment by dougbw** [comment]
Here is an example of the automatic DNS search domain working:
![image](https://github.com/user-attachments/assets/4dbf8aa3-6b7d-4468-99f6-a85c6b5bfa5e)

It should just work automatically, but if it doesn't then it is likely an issue with your OS configuration as afaik it is standard across Windows, MacOs, Linux, and Android.

**Comment by reeseovine** [comment]
Thanks for the answer! Unfortunately adding a search domain doesn't seem to work, I just get "name or service unknown" from `ping`. I tried adding the search domain by editing the connection in `nmtui` with and without a leading dot. Maybe it's another cache thing and I just have to wait 😅

**Comment by dougbw** [comment]
It is most likely an issue with your device, it would be worth testing from another device if you have one available but ultimately this functionality is handled by the OS rather than the DNS server.

What OS are you using? Assuming it is a Linux variation based on your comment above then the search domain is set in `/etc/resolv.conf` e.g:

```
search omada.home
```

**Comment by reeseovine** [comment]
Aha! You got me on the right track, but because it's NixOS I hit a few snags. 🙃 It's my issue to figure out so I'll leave you be. Thank you for the help so far!
