### ISSUE TITLE
Tutorial please 

### ISSUE THREAD

**Issue by Damiexxi2** [dougbw/coredns_omada#54]
Hi,

I'm trying to follow the instructions.

Got as far as 
![image](https://github.com/user-attachments/assets/ffcb2a5b-383d-4d0e-b8eb-72af5264fd56)

But what to do next I'm completed lost.

I'm ruining it off a docker in proxmox.

Would great appreciate a little more details in the setup process please

**Comment by dougbw** [comment]
Hi,

The setup guide is here: https://github.com/dougbw/coredns_omada/blob/main/docs/getting-started.md#getting-started

It looks like you have got CoreDNS running already, so the next step is to set the DNS server to your containers IP address in the LAN settings for your network.
