### ISSUE TITLE
Reverse DNS?

### ISSUE THREAD

**Issue by Daniel15** [dougbw/coredns_omada#55]
Does this support reverse DNS (PTR)? In systems like AdGuard Home at the moment, I just see IP addresses for the clients, but it supports showing hostnames via reverse DNS lookups. I'd like to avoid having to maintain a DNS zone manually, so your project looks like an interesting idea.

**Comment by GibsonSoft** [comment]
It does! I'm using this same setup.

In ADH I have two forwarding rules: one that goes to Unbound for all outbound requests, then another for all of my locals. That way I avoid that extra hop of having to go through CoreDNS first.

![image](https://github.com/user-attachments/assets/c49cc89e-c610-4e00-876e-9858df1642f6)

![image](https://github.com/user-attachments/assets/db180be6-1e03-413e-8d5b-8e09b6edf424)

**Comment by GibsonSoft** [comment]
One more sample from the query log:
![image](https://github.com/user-attachments/assets/0a2543b8-5a60-4d98-adad-4c2973fad600)

**Comment by dougbw** [comment]
As mentioned above reverse DNS is supported - the reverse zone is created automatically and does not need any additional configuration. I have updated the readme to highlight the supported features.
