### ISSUE TITLE
Multiple Sites on one Omada Controller

### ISSUE THREAD

**Issue by tangent360** [dougbw/coredns_omada#7]
I have 2 sites configured on an OC200.  There is a site-to-site always on VPN between the two sites.  As a result, clients on one site subnet can communicate directly with clients on the other.  Is there a way in the config/env variables to specify that coredns-omada should read the client entries for both sites off the controller?  e.g. using a list [“site_one”, “site_two”]
Alternatively, can I run a second instance of coredns-omada (listening on a port other than 53) which serves as the nameserver for the second site and then chain the upstream nameservers from first coredns to second to 8.8.8.8?   (or, instead of chaining, just add the second coredns instance to a list of upstream resolvers for the first instance) . Thanks.

**Comment by tangent360** [comment]
I could not get this to work across multiple Omada sites using a docker container per site, despite trying several different configurations and approaches - it would work for one site but not the other and forwarding to external DNS was not working right when two containers were running.

I believe the single site limitation stems from go-omada/Controller struct having a single siteID field. I extended this to also have an array of siteIds and added a method called getAllSiteIds which is called from the Controller.Login method such that every controller login request also populates the array of all available siteIds.  From there I extended networks.go, devices.go and clients.go to have GetAllNetworks, GetAllDevices and GetAllClients methods respectively.  These GetAllX methods disregard the siteId and iterate through all available siteIds to build a superset of networks, clients and devices. Then it was simply a case of modifying coredns-omada/update.go to call the GetAllX methods instead of the single site variants. 
This now pulls all clients and devices for each site that the login user is permissioned to see.

I assume there are vastly superior ways to structure this.  I know nothing about the Omada API and didn't know if it has a "allSites" site-key which would make this much easier.  I know little about DNS and had not read a line of Go before yesterday ... so I'm happy to send a pull request for the code but it's just hacked together. I don't know if there is a lot of point in beautifying it if TPLink are going to come out with controller based DNS in the future. (The go-omada library obviously has value well beyond DNS).  
It does work though and it's really nice to finally have multi-site DNS for Omada.  Ty Doug for writing this.

**Comment by dougbw** [comment]
Hello,

First of all thanks for taking the time on this.

Running 2 instances of Coredns on the same machine would be possible but it gets complicated as you would need multiple IP addresses with each instance bound to a different IP address as all DNS clients will expect the server to be listening on port 53. 

As you have seen, currently the plugin was designed to retrieve clients/devices from a single site only. I will take a look in to adding support for multiple sites and how it would be structured, but I am glad you managed to get it working in the mean time.

Many thanks,
Doug

**Comment by dougbw** [comment]
FYI I have added support for this into the latest release. Testing has been pretty limited as I only actually have 1 network site on my network with any devices/clients but in theory it should work.
